### ISSUE TITLE
add HMI to show the log

### ISSUE THREAD

**Issue by runtimevic** [FellowWithLaptop/FB_CaseStateMachine#1]
Hello,
an HMI could be added to show the log.
thanks you.

**Comment by FellowWithLaptop** [comment]
In this example I only want to show the possibility to use an FB for a state machine. The logger functionality was just nice to have and probably needs to be adapted to the application. Not everyone uses the same HMI so I don't want to make an example. The messages are written directly to the TwinCAT event logger in the example and can be displayed in the TwinCAT HMI.
